# .travis.yml
dist: trusty
sudo: required
language: node_js

node_js:
  - "7"

cache:
  directories:
    - "node_modules"

install:
 - npm install
 - npm install -g codecov

script:
 - npm run build
 - npm run generate

after_success:
  - set -e
  - sudo apt-get install -y lftp
  - lftp -c "
      set ftps:initial-prot '';
      set ftp:ssl-force true;
      set ftp:ssl-protect-data true;
      set ssl:verify-certificate false;
      open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST:21;
      mirror -eRv -P 10 $FTP_DIR .;
      quit;"
  - codecov
  - chmod +x discord.sh
  - ./discord.sh success

after_failure:
  - chmod +x discord.sh
  - ./discord.sh failure